### ISSUE TITLE
[SW-04] Stack Vertically List and Recipe Images

### ISSUE THREAD

**Issue by mgdeleon** [QSpice/qspice-ios#4]
In "Order" tab

**Comment by afiorito** [comment]
@mgdeleon @FozAhm do we really want to do this? I feel like it won't look good.

**Comment by FozAhm** [comment]
I am not sure but it will fill up the space very nicely. Idk if the UI experience will be strenuous on the user since they will have to move their finger more

**Comment by mgdeleon** [comment]
It would fill the space more. Maybe at least center the images so they’re not just on top of the page. It’s just for balance.
